ARCHS = armv7 arm64
include theos/makefiles/common.mk

TOOL_NAME = ccsettingssupport
ccsettingssupport_FILES = main.mm
ccsettingssupport_INSTALLPATH = /usr/bin/
ccsettingssupport_FRAMEWORKS = CoreFoundation

include $(THEOS_MAKE_PATH)/tool.mk
